apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-code-app.fullname" . }}-ollama
  labels:
    {{- include "ai-code-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-code-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ollama